export const GlobalInitialState = {
    form: {
      name: "",
      email: "",
      mobile: "",
      role: "",
      password: "",
      confirmPassword: "",
      financialYear:"",
      aadharNumber:"",
      passbookName:"",
      DOB:"",
      gender:"",
      socialCategory:"",
      farmerCategory:"",
      farmerType:"",
      primaryOccupation:"",
      relativeType:"",
      relativeName:"",
      stateName:"",
      district:"",
      subDistrict:"",
      village:"",
      address:"",
      pinCode:"",
      bank:"",
      branch:""
    },
    errors: {
      name:"",
      email:"",
      mobile:"",
      role:"",
      password:"",
      confirmPassword:"",
      financialYear:"",
      aadharNumber:"",
      passbookName:"",
      DOB:"",
      gender:"",
      socialCategory:"",
      farmerCategory:"",
      farmerType:"",
      primaryOccupation:"",
      relativeType:"",
      relativeName:"",
      stateName:"",
      district:"",
      subDistrict:"",
      village:"",
      address:"",
      pinCode:"",
      bank:"",
      branch:""
    },
}