export const VALIDATION_MSG = {
    name:"Enter Name!",
    nameFormat:"Only alphabets allowed!",
    email:"Email ID requires!",
    emailFormat:"Inavlid email!",
    mobile:"Mobile number requires!",
    mobileFormat:"Invalid mobile number!",
    password:"Password requires!",
    passwordLength:"Minimum 8 characters!",
    confirmPasswordRequire:"Confirm password requires!",
    confirmPassword:"Passwords do not match!",
    roleSelection:"Please select a role!",
    financialYears:"Select the financial year!",
    aadharNumber:"Enter Valid Aadhar number!",
    DOB:"Enter DOB in DD/MM/YYYY format!",
    socialCategoryValidation:"Select the social category!",
    farmerCategoryValidation:"Select the farmer category!",
    farmerTypeValidation:"Select the farmer type!",
    farmerOccupationValidation:"Select the farmer primary occupation!",
    relativeTypeValidation:"Select the farmer relative type!",
    stateNameValidation:"Select the state name!",
    districtValidation:"Select the district name!",
    subDistrictValidation:"Select the sub-district name!",
    villageValidation:"Select the village name!",
    addressValidation:"Enter the residential address!",
    pinCodeValidation:"Enter the pin code!",
    bankValidation:"Select bank name!",
    branchValidation:"Select branch name!",
    accountNumber:"Enter Account number!",
    accountNumberLength:"Minimum 8 characters!",
    confirmAccountNumber:"Account number must be matched!",
    confirmAccountRequire:"Confirm account number requires!",
}